apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    # This tells K8s to use the Nginx controller we just enabled
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kubo-lab.test         # <--- Your "Fake" Domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service   # <--- Must match your Service name
            port:
              number: 80        # <--- The SERVICE port (Internal)