apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-server
  template:
    metadata:
      labels:
        app: apache-server
    spec:
      containers:
      - name: apache-container
        image: httpd:alpine
        ports:
        - containerPort: 80